### ISSUE TITLE
XML Parsing: XML parsing: An unexpected error has occurred in the XML parser.

### ISSUE THREAD

**Issue by adityafeb22** [arvindshmicrosoft/MillionSongDatasetinSQLServer#1]
Following code
 `INSERT dbo.unique_tracks
SELECT        TrackId, SongId, ArtistName, SongTitle
FROM OPENROWSET(BULK 'C:\MSD\unique_tracks.txt', 
			FORMATFILE = 'C:\MSD\echonesttracks.fmt', 
			CODEPAGE = '65001'
			) AS RawData
GO` is returning XML parser error....

Tried different ways to solve this but never get through, any help here is appreciated...

**Comment by arvindsh** [comment]
Hi Aditya please use the RAW view in GitHub to download the files or git clone the repo. Most likely you have downloaded the HTML version of the FMT files. You need the Raw version...

**Comment by adityafeb22** [comment]
Thanks a lot Arvind!!! This worked :)
