### ISSUE TITLE
About the Import Source Step

### ISSUE THREAD

**Issue by kelibox** [arvindshmicrosoft/MillionSongDatasetinSQLServer#2]
I try to excute the "1_ImportSourceTables.sql", 
but " INSERT dbo.unique_tracks"  is fail and  "INSERT dbo.[train_triplets]" is ok.
The Error of  "INSERT dbo.unique_tracks" happened on "<" missing.
What happened ? 
My guest is terminator problem( the terminiator is  `<SEP>`).
What can i do to overcome this problem?
Thank you!

PS:Environment SQL 2017 ctp 2.1

**Comment by arvindsh** [comment]
There was a bug with the echonesttracks.xml format file. I've fixed it now. Can you please pull the latest version and check again?

**Comment by kelibox** [comment]
I try again,it work .thanks
